sources_path : "src/"
index_path: src/index.html
netlify_site_name : keen-lichterman-903b62
production_branch : master
editable_selector : "a, p, h1,h2,h3,h4,h5, button,ul,li"
has_components : "false"
