index_path: "src/test_page_one.html"
sources_path : "src/"
netlify_site_name : keen-lichterman-903b62
production_branch : master
# editable_selector : "a, p, h1,h2,h3,h4,h5, button,ul,li"
has_components : true
